enable_testing()

Include(FetchContent)

FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v3.8.1 # or a later release
)

FetchContent_MakeAvailable(Catch2)

add_executable(testthreadpool testthreadpool.cpp)
target_link_libraries(testthreadpool PRIVATE mini-lib Catch2::Catch2WithMain)

add_executable(testargparser testargparser.cpp)
target_link_libraries(testargparser PRIVATE mini-lib Catch2::Catch2WithMain)

include(Catch)
catch_discover_tests(testthreadpool)
catch_discover_tests(testargparser)
